Vagrant.configure(2) do |config|

  # CentOS 6
  config.vm.define "yum-cron-centos6" do |centos6|
    centos6.vm.box = "samdoran/centos6"
    centos6.vm.hostname = "yum-cron-centos6"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "yum-cron-centos6"
      vbox.cpus = 1
      vbox.memory = 128
    end
  end

  # CentOS 7
  config.vm.define "yum-cron-centos7" do |centos7|
    centos7.vm.box = "samdoran/centos7"
    centos7.vm.hostname = "yum-cron-centos7"
    config.vm.provider "virtualbox" do |vbox|
      vbox.name = "yum-cron-centos7"
      vbox.cpus = 1
      vbox.memory = 512
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant.yml"
    ansible.compatibility_mode = "2.0"
  end

end
